-- Script para adicionar campo CATEGORY à tabela INGREDIENTS
-- Execute este script no banco Firebird existente

-- Adiciona a coluna CATEGORY à tabela INGREDIENTS, se ela não existir
EXECUTE BLOCK AS BEGIN
    IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'INGREDIENTS' AND RDB$FIELD_NAME = 'CATEGORY')) THEN
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE INGREDIENTS ADD CATEGORY VARCHAR(100)';
    END
END;
